app_new_categories:
    path:      /categories
    defaults: { _controller: AppBundle:Category:new }
    methods:  [POST]
    
app_list_categories:
    path:      /categories
    defaults: { _controller: AppBundle:Category:list }
    methods:  [GET]
    
app_new_products:
    path:      /products
    defaults: { _controller: AppBundle:Product:new }
    methods:  [POST]
    
app_list_products:
    path:      /categories/{id}/products/
    defaults: { _controller: AppBundle:Product:list }
    methods:  [GET]
    requirements:
        id: '\d+'
    
